spring:
  profiles: H2

---

spring:
  profiles: Postgre
  datasource:
    hikari:   ## default connection pool
      connectionTimeout: 20000
      maximumPoolSize: 5
    url : jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto : create  #drop n create table again, good for testing, comment this in production
